# Generated by Django 2.1.3 on 2018-12-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanager',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
