# Generated by Django 2.1.3 on 2018-11-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='restaurant',
        ),
    ]
