# Generated by Django 2.1.3 on 2018-11-27 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181127_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='username',
        ),
        migrations.AddField(
            model_name='authuser',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
    ]
