# Generated by Django 2.1.3 on 2018-11-27 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181127_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='restaurant',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='restaurants'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authuser',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Phone Number'),
        ),
    ]
